import '../style.css'

export { createPlatformUi, usePlatformUi, resolveUi, PLATFORM_UI } from './config'
export type { PlatformUi, PlatformUiOptions, NotifyKind } from './config'
export type { JobFilters, AuditFilters } from './types'
export { usePoll } from './usePoll'
export { useCursorPages, mergePages, type CursorPagesOptions } from './useCursorPages'
export { useEventTail, type EventTailOptions } from './useEventTail'
export { useJobActions, type JobAction } from './useJobActions'

export { default as PlatformLink } from './components/PlatformLink.vue'
export { default as StateChip } from './components/StateChip.vue'
export { default as SubjectLink } from './components/SubjectLink.vue'
export { default as JobsTable } from './components/JobsTable.vue'
export { default as JobsBrowser } from './components/JobsBrowser.vue'
export { default as JobDetail } from './components/JobDetail.vue'
export { default as JobEventLog } from './components/JobEventLog.vue'
export { default as AuditTable } from './components/AuditTable.vue'
export { default as AuditBrowser } from './components/AuditBrowser.vue'
export { default as ChatLine } from './components/ChatLine.vue'
export { default as ChatEmote } from './components/ChatEmote.vue'
